config/routes.rb
Rails.application.routes.draw do
  
  resources :carts

  # Root path of the application
  root 'dashboard#index'
  
  #Routes for products CRUD
  resources :products do
    resources :carts, only: [:new, :edit]
  end
  
  #Routes for orders CRUD
  resources :carts,  except: [:new, :edit]
  
  #Routes for orders CRUD
  resources :orders

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  #Associations
  belongs_to :product
  
  #Validations
  validates_presence_of :quantity
  validates :quantity, :numericality => { :greater_than => 0 }
  
  attr_accessor :product_image
  
  #scope for active products
  scope :created_between, -> (start_date, end_date  = 0) { where("DATE(created_at) >= ? AND DATE(created_at) <= ?", start_date  - end_date.days, start_date )}
  
  delegate :title, to: :product, allow_nil: true, prefix: true
  delegate :img_path, to: :product, allow_nil: true, prefix: true
  
  #Create product image URL
  before_save :calculate_price
  
  def calculate_price
    self.price = product.price
    self.value = self.quantity * self.price
  end
  
  def order_status
    status ? "Fulfilled" : "UnFulfilled"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
    
  #Associations
  has_many :order_products
  has_many :products, through: :order_products

  #scope for active products
  scope :fulfilled, -> { where('status =?', true) }
  scope :unfulfilled, -> { where('status =?', false) }
  scope :created_between, -> (start_date, end_date  = 0) { where("DATE(created_at) >= ? AND DATE(created_at) <= ?", start_date  - end_date.days, start_date )}
  
  def order_status
    status ? "Fulfilled" : "UnFulfilled"
  end
  
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  
  #Associations
  belongs_to :order
  belongs_to :product
  
  delegate :title, to: :product, allow_nil: true, prefix: true
  delegate :img_path, to: :product, allow_nil: true, prefix: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  #Associations
  has_many :order_products
  has_many :orders, through: :order_products
  
  #Validations
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :price
  validates :price, :numericality => { :greater_than => 0 }
  
  attr_accessor :img_path
  
  #scope for active products
  scope :active, -> { where('active =?', true) }
  
  PATH = ['product1.jpg','product2.jpg','product3.jpg','product4.jpg','product5.jpg']
  
  #Create product image URL
  before_create :default_url
  
  def default_url
    self.url = PATH[rand(5)]
  end
  
  def img_path
    "/products/" + self.url
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update, :destroy]
  before_action :set_product, only: [:edit, :new]

  # GET /carts
  def index
    @carts = Cart.all.order(created_at: :desc)
  end

  # GET /carts/1
  def show
  end
  
  # GET /carts/1
  def edit
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to carts_path, notice: 'Cart was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  # PATCH/PUT /carts/1
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to carts_path, notice: 'Cart was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
    end
  end

  private
    # Loading cart
    def set_cart
      @cart = Cart.where('id =?',params[:id]).first
    end
    
    def set_product
      @product = Product.where('id =?',params[:product_id]).first
    end
    
    def cart_params
      params.require(:cart).permit(:product_id, :quantity, :status)
    end
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @today = Order.created_between(Date.today)
    @week = Order.created_between(Date.today - 1.days, 7)
    @month = Order.created_between(Date.today - 1.days, 30)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:edit, :new]

  # GET /orders
  def index
    @orders = Order.all.order(created_at: :desc)
  end

  # GET /orders/1
  def show
  end
  
  # GET /orders/1
  def edit
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # POST /orders
  def create
    @cart = Cart.all
    @order = Order.create(value: @cart.sum(:value))
    @cart.each { |cart| @order.order_products.create(product_id: cart.product_id, quantity: cart.quantity, price: cart.price) }
    @cart.destroy_all
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
    end
  end
  
  # PATCH/PUT /orders/1
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
    end
  end

  private
    # Loading order
    def set_order
      @order = Order.where('id =?',params[:id]).first
    end
    
    def set_product
      @product = Product.where('id =?',params[:product_id]).first
    end
    
    def order_params
      params.require(:order).permit(:status)
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :set_product, only: [:edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.active.order(created_at: :desc)
  end

  # GET /products/1
  def show
    redirect_to products_path, notice: "You don't have access for this page"
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /products/1
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  def destroy
    @product.update(:active => false)
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
     end
  end

  private
    # Loading product
    def set_product
      @product = Product.where('id =?',params[:id]).first
    end

    # Strong parameters.
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_form.html.erb
<div style="display: none" class="status alert alert-success"></div>
<%= form_for @cart, class: "contact-form row", id:"main-contact-form" do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h3>
      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group col-md-12">
    <div class="form-group col-md-6"><%= image_tag @product.img_path, size: "110x110" %></div>
    <div class="form-group col-md-6"><h3><%= @product.title %> - $<%= @product.price %></h3></div>
  </div>
  <div class="form-group col-md-12">
	<%= f.text_field :quantity, placeholder: :Quantity, required: :required, class: "form-control" %>
    </div>
  <%= f.hidden_field :product_id, value: params[:product_id] %>
  <div class="form-group col-md-12">
	<input type="submit" value="Submit" class="btn btn-primary pull-right" name="submit">
    </div>
<% end %>

app/views/carts/backup/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/backup/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/backup/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Price</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.quantity %></td>
        <td><%= cart.price %></td>
        <td><%= cart.value %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/backup/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/backup/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @cart.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cart.price %>
</p>

<p>
  <strong>Value:</strong>
  <%= @cart.value %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/carts/edit.html.erb
<div class="container" id="contact-page">
    <div class="bg">	    	    	
	    <div class="row">  	
		    <div class="col-sm-3"></div>
		    <div class="col-sm-6">
			    <div class="contact-form">
				<h2 class="title text-center">Change Cart</h2>
				<%= render 'form' %>
			    </div>
		    </div>
		    <div class="col-sm-3"></div>    			
	    </div>  
    </div>	
</div>

app/views/carts/index.html.erb
<section id="cart_items">
    <div class="container">	    
	    <div class="table-responsive cart_info">
		    <table class="table table-condensed">
			    <thead>
				    <tr class="cart_menu">
					    <td class="image">Item</td>
					    <td class="description"></td>
					    <td class="price">Price</td>
					    <td class="quantity">Quantity</td>
					    <td class="total">Total</td>
					    <td></td>
					    <td></td>
				    </tr>
			    </thead>
			    <tbody>
				<% @carts && @carts.each_with_index do |cart, index| %>
				    <tr>
					    <td class="cart_product">
						    <a href=""><%= image_tag cart.product_img_path, size: "110x110" %></a>
					    </td>
					    <td class="cart_description">
						    <h4><%= cart.product_title %></h4>
					    </td>
					    <td class="cart_price">
						    <p>$<%= cart.price %></p>
					    </td>
					    <td class="cart_quantity">
						    <p><%= cart.quantity %></p>
					    </td>
					    <td class="cart_total">
						    <p class="cart_total_price">$<%= cart.value %></p>
					    </td>
					    <td class="cart_delete">
						<%= link_to 'Change ', edit_product_cart_path(product_id: cart.try(:product).try(:id), id: cart.try(:id)), class: "cart_quantity_delete" %>
					    </td>
					    <td class="cart_delete">
						<%= link_to 'Remove', cart_path(cart.try(:id)), method: :delete, class: "cart_quantity_delete" %>
					    </td>
				    </tr>
				  <% end %>
				<% if @carts.present? %>
				<tr>
				  <td colspan="3">&nbsp;</td>
				  <td colspan="3"> <span>Total : $<%= @carts.sum(:value) %></span></td>
				</tr>
				<tr>
				  <td colspan="3">&nbsp;</td>
				  <td colspan="3"> <a href="/orders" class="btn btn-primary" data-method = 'post' >Checkout</a></td>
				</tr>
				<% end %>
			    </tbody>
		    </table>
	    </div>
    </div>
</section>

app/views/carts/new.html.erb
<div class="container" id="contact-page">
    <div class="bg">	    	    	
	    <div class="row">  	
		    <div class="col-sm-3"></div>
		    <div class="col-sm-6">
			    <div class="contact-form">
				<h2 class="title text-center">New Cart</h2>
				<%= render 'form' %>
			    </div>
		    </div>
		    <div class="col-sm-3"></div>    			
	    </div>  
    </div>	
</div>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @cart.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cart.price %>
</p>

<p>
  <strong>Value:</strong>
  <%= @cart.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @cart.status %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/dashboard/index.html.erb
<section id="cart_items">
    <div class="container">	    
	    <div class="table-responsive cart_info">
		    <table class="table table-condensed">
			    <caption><h2>Orders Summary</h2></caption>
			    <thead>
				    <tr class="cart_menu">
					    <td class="image">Days</td>
					    <td class="description">Fulfilled</td>
					    <td class="price">UnFulfilled</td>
					    <td class="total">Total</td>
					    <td></td>
					    <td></td>
				    </tr>
			    </thead>
			    <tbody>
				    <tr>
					    <td class="cart_product">
						    <a href="#">Today</a>
					    </td>
					    <td class="cart_description">
						    <p><%= @today.fulfilled.count %></p>
					    </td>
					    <td class="cart_price">
						    <p><%= @today.unfulfilled.count %></p>
					    </td>
					    <td class="cart_quantity">
						    <p><%= @today.count %></p>
					    </td>
				    </tr>
				    <tr>
					    <td class="cart_product">
						    <a href="">Last 7 Days</a>
					    </td>
					    <td class="cart_description">
						    <p><%= @week.fulfilled.count %></p>
					    </td>
					    <td class="cart_price">
						    <p><%= @week.unfulfilled.count %></p>
					    </td>
					    <td class="cart_quantity">
						    <p><%= @week.count %></p>
					    </td>
				    </tr>
				    <tr>
					    <td class="cart_product">
						    <a href="">Last 30 days</a>
					    </td>
					    <td class="cart_description">
						    <p><%= @month.fulfilled.count %></p>
					    </td>
					    <td class="cart_price">
						    <p><%= @month.unfulfilled.count %></p>
					    </td>
					    <td class="cart_quantity">
						    <p><%= @month.count %></p>
					    </td>
				    </tr>
			    </tbody>
		    </table>
	    </div>
    </div>
</section>

app/views/layouts/_footer.html.erb
<footer id="footer"><!--Footer-->	<p></p>
    <div class="footer-bottom">
	    <div class="container">
		    <div class="row">
			    <p class="pull-left">Copyright © 2013 E-SHOPPER. All rights reserved.</p>
			    <p class="pull-right">Designed by <span><a target="_blank" href="#">Saravana</a></span></p>
		    </div>
	    </div>
    </div>
    
</footer><!--/Footer-->

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>E-Shopper</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>    
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]--> 
</head><!--/head-->

app/views/layouts/_header.html.erb
<header id="header"><!--header-->
    <div class="header-middle"><!--header-middle-->
	    <div class="container">
		    <div class="row">
			    <div class="col-sm-4">
				    <div class="logo pull-left">
					    <a href="/"><img src="/assets/home/logo.png" alt="" /></a>
				    </div>						
			    </div>
			    <div class="col-sm-8">
				    <div class="shop-menu pull-right">
					    <ul class="nav navbar-nav">
						    <li><a href="/products"><i class="fa fa-star"></i> Goods</a></li>
						    <li><a href="/products/new"><i class="fa fa-crosshairs"></i> Add item</a></li>
						    <li><a href="/carts"><i class="fa fa-shopping-cart"></i> Carts</a></li>						    
						    <li><a href="/orders"><i class="fa fa-lock"></i> Orders</a></li>						    
					    </ul>
				    </div>
			    </div>
		    </div>
	    </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
    </div><!--/header-bottom-->
</header><!--/header-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render "layouts/head" %>
<body>
  <%= render "layouts/header" %>
  <%= yield %>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/orders/_form.html.erb
<div style="display: none" class="status alert alert-success"></div>
<%= form_for @order, class: "contact-form row", id:"main-contact-form" do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>
      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group col-md-12">
	<%= f.select :status, options_for_select([["Fulfilled" ,true],["UnFulfilled", false]], @order.status), class: "form-control" %>
    </div>
  <div class="form-group col-md-12">
	<input type="submit" value="Submit" class="btn btn-primary pull-right" name="submit">
    </div>
<% end %>

app/views/orders/edit.html.erb
<div class="container" id="contact-page">
    <div class="bg">	    	    	
	    <div class="row">  	
		    <div class="col-sm-3"></div>
		    <div class="col-sm-6">
			    <div class="contact-form">
				<h2 class="title text-center">Change Order</h2>
				<%= render 'form' %>
			    </div>
		    </div>
		    <div class="col-sm-3"></div>    			
	    </div>  
    </div>	
</div>

app/views/orders/index.html.erb
<section id="cart_items">
    <div class="container">	    
	    <div class="table-responsive cart_info">
		    <table class="table table-condensed">
			    <thead>
				    <tr class="cart_menu">
					    <td class="description"></td>
					    <td class="description">No</td>
					    <td class="price">Total Products</td>
					    <td class="quantity">Total Quantity</td>
					    <td class="total">Price</td>
					    <td class="total">Status</td>
					    <td></td>
				    </tr>
			    </thead>
			    <tbody>
				<% @orders && @orders.each_with_index do |order, index| %>
				    <tr>
					    <td class="cart_description">
						    <p></p>
					    </td>
					    <td class="cart_description">
						    <p><%= index + 1 %></p>
					    </td>
					    <td class="cart_price">
						    <p><%= order.order_products.count %></p>
					    </td>
					    <td class="cart_quantity">
						    <p><%= order.order_products.sum(:quantity) %></p>
					    </td>
					    <td class="cart_total">
						    <p>$<%= order.value %></p>
					    </td>
					    <td class="cart_total">
						    <p><%= link_to order.order_status,  edit_order_path(order)%></p>
					    </td>
					    <td class="cart_delete">
						<%= link_to 'Show Order ', order_path(order), class: "btn btn-primary" %>
					    </td>
				    </tr>
				  <% end %>
			    </tbody>
		    </table>
	    </div>
    </div>
</section>

app/views/orders/new.html.erb
<div class="container" id="contact-page">
    <div class="bg">	    	    	
	    <div class="row">  	
		    <div class="col-sm-3"></div>
		    <div class="col-sm-6">
			    <div class="contact-form">
				<h2 class="title text-center">New order</h2>
				<%= render 'form' %>
			    </div>
		    </div>
		    <div class="col-sm-3"></div>    			
	    </div>  
    </div>	
</div>

app/views/orders/show.html.erb
<section id="cart_items">
    <div class="container">	    
	    <div class="table-responsive cart_info">
		    <table class="table table-condensed">
			    <thead>
				    <tr class="cart_menu">
					    <td class="image">Item</td>
					    <td class="description"></td>
					    <td class="price">Price</td>
					    <td class="quantity">Quantity</td>
					    <td class="quantity">Total</td>
				    </tr>
			    </thead>
			    <tbody>
				<% @order && @order.order_products.each_with_index do |order_product, index| %>
				    <tr>
					    <td class="cart_product">
						    <a href=""><%= image_tag order_product.product_img_path, size: "110x110" %></a>
					    </td>
					    <td class="cart_description">
						    <h4><%= order_product.product_title %></h4>
					    </td>
					    <td class="cart_price">
						    <p>$<%= order_product.price %></p>
					    </td>
					    <td class="cart_quantity">
						    <p><%= order_product.quantity %></p>
					    </td>
					    <td class="cart_total">
						    <p class="cart_total_price">$<%= order_product.price *  order_product.quantity %></p>
					    </td>
				    </tr>
				  <% end %>
				  
				<tr>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
				  <td>&nbsp;</td>
				  <td>Total :</td>
				  <td> <p class="cart_total_price">$<%= @order.value %></p></td>
				</tr>
			    </tbody>
		    </table>
	    </div>
    </div>
</section>

app/views/products/_form.html.erb
<div style="display: none" class="status alert alert-success"></div>
<%= form_for @product, class: "contact-form row", id:"main-contact-form" do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
	<h3><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
	<ul>
	<% @product.errors.full_messages.each do |message| %>
	  <li>* <%= message %></li>
	<% end %>
	</ul>
      </div>
    <% end %>
    <div class="form-group col-md-12">
	<%= f.text_field :title, placeholder: :Title, required: :required, class: "form-control" %>
    </div>    
    <div class="form-group col-md-12">
	<%= f.text_area :description, placeholder: :Description, required: :required, id: :message, class: "form-control" %>
    </div>
    <div class="form-group col-md-12">
	<%= f.text_field :price, placeholder: :Price, required: :required, class: "form-control" %>
    </div>                        
    <div class="form-group col-md-12">
	<input type="submit" value="Submit" class="btn btn-primary pull-right" name="submit">
    </div>
<% end %>

app/views/products/_left_static_content.html.erb
<div class="left-sidebar">
    <h2>Offers</h2>
				
    <!--shipping-->
    <div class="shipping text-center">
	    <img src="/assets/home/shipping.jpg" alt="" />
    </div><!--/shipping-->

</div>

app/views/products/edit.html.erb
<div class="container" id="contact-page">
    <div class="bg">	    	    	
	    <div class="row">  	
		    <div class="col-sm-2"></div>
		    <div class="col-sm-8">
			    <div class="contact-form">
				<h2 class="title text-center">Edit Product</h2>
				<%= render 'form' %>
			    </div>
		    </div>
		    <div class="col-sm-2"></div>    			
	    </div>  
    </div>	
</div>

app/views/products/index.html.erb
<section>
    <div class="container">
	    <div class="row">
		    <div class="col-sm-3">
			    <%= render "products/left_static_content"%>
		    </div>
		    
		    <div class="col-sm-9 padding-right">
			    <div class="features_items"><!--features_items-->
				    <h2 class="title text-center">Features Items</h2>
				    <% @products && @products.each do |product| %>
				    <div class="col-sm-4">
					    <div class="product-image-wrapper">
						    <div class="single-products">
								    <div class="productinfo text-center">
									    <%= image_tag product.img_path %>
									    <h2>$<%= product.price %></h2>
									    <p><%= product.title %></p>
									    <%= link_to "<i class='fa fa-shopping-cart'></i>Add to cart".html_safe, new_product_cart_path(product_id: product.try(:id)), class: "btn btn-default add-to-cart" %>
								    </div>
								    <div class="product-overlay">
									    <div class="overlay-content">
										    <h2>$<%= product.price %></h2>
										    <h3><%= product.title %></h3>
										    <p><%= product.description %></p>
										    <%= link_to "<i class='fa fa-shopping-cart'></i>Add to cart".html_safe, new_product_cart_path(product_id: product.try(:id)), class: "btn btn-default add-to-cart" %>									    </div>
								    </div>
						    </div>	
						    <div class="choose">
							    <ul class="nav nav-pills nav-justified">
								    <li><%= link_to "<i class='fa fa-plus-square'></i>Edit".html_safe, edit_product_path(product.id)%></li>
								    <li><%= link_to "<i class='fa fa-plus-square'></i>Delete".html_safe, product_path(product.id), method: :delete%></li>
							    </ul>
						    </div>
					    </div>
				    </div>
				    <% end %>																
			    </div><!--features_items-->					
		    </div>
	    </div>
    </div>
</section>

app/views/products/new.html.erb
<div class="container" id="contact-page">
    <div class="bg">	    	    	
	    <div class="row">  	
		    <div class="col-sm-2"></div>
		    <div class="col-sm-8">
			    <div class="contact-form">
				<h2 class="title text-center">Add new product</h2>
				<%= render 'form' %>
			    </div>
		    </div>
		    <div class="col-sm-2"></div>    			
	    </div>  
    </div>	
</div>